// Code generated by controller-gen. DO NOT EDIT.

package applyconfigurations

import (
	v1alpha1 "github.com/openzro/openzro-operator/api/v1alpha1"
	apiv1alpha1 "github.com/openzro/openzro-operator/pkg/applyconfigurations/api/v1alpha1"
	internal "github.com/openzro/openzro-operator/pkg/applyconfigurations/internal"
	runtime "k8s.io/apimachinery/pkg/runtime"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	managedfields "k8s.io/apimachinery/pkg/util/managedfields"
)

// ForKind returns an apply configuration type for the given GroupVersionKind, or nil if no
// apply configuration type exists for the given GroupVersionKind.
func ForKind(kind schema.GroupVersionKind) interface{} {
	switch kind {
	// Group=openzro.io, Version=v1alpha1
	case v1alpha1.SchemeGroupVersion.WithKind("ContainerOverride"):
		return &apiv1alpha1.ContainerOverrideApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("CrossNamespaceReference"):
		return &apiv1alpha1.CrossNamespaceReferenceApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("DNSZoneReference"):
		return &apiv1alpha1.DNSZoneReferenceApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("Group"):
		return &apiv1alpha1.GroupApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("GroupReference"):
		return &apiv1alpha1.GroupReferenceApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("GroupSpec"):
		return &apiv1alpha1.GroupSpecApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("GroupStatus"):
		return &apiv1alpha1.GroupStatusApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("NetworkResource"):
		return &apiv1alpha1.NetworkResourceApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("NetworkResourceSpec"):
		return &apiv1alpha1.NetworkResourceSpecApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("NetworkResourceStatus"):
		return &apiv1alpha1.NetworkResourceStatusApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("NetworkRouter"):
		return &apiv1alpha1.NetworkRouterApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("NetworkRouterSpec"):
		return &apiv1alpha1.NetworkRouterSpecApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("NetworkRouterStatus"):
		return &apiv1alpha1.NetworkRouterStatusApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("SetupKey"):
		return &apiv1alpha1.SetupKeyApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("SetupKeySpec"):
		return &apiv1alpha1.SetupKeySpecApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("SetupKeyStatus"):
		return &apiv1alpha1.SetupKeyStatusApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("SidecarProfile"):
		return &apiv1alpha1.SidecarProfileApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("SidecarProfileSpec"):
		return &apiv1alpha1.SidecarProfileSpecApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("SidecarProfileStatus"):
		return &apiv1alpha1.SidecarProfileStatusApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("WorkloadOverride"):
		return &apiv1alpha1.WorkloadOverrideApplyConfiguration{}

	}
	return nil
}

func NewTypeConverter(scheme *runtime.Scheme) managedfields.TypeConverter {
	return managedfields.NewSchemeTypeConverter(scheme, internal.Parser())
}
