// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

// DNSZoneReferenceApplyConfiguration represents a declarative configuration of the DNSZoneReference type for use
// with apply.
//
// DNSZoneReference references a openZro DNS zone by domain name.
type DNSZoneReferenceApplyConfiguration struct {
	// Name is the domain name of an existing openZro DNS zone, e.g. "example.com".
	Name *string `json:"name,omitempty"`
}

// DNSZoneReferenceApplyConfiguration constructs a declarative configuration of the DNSZoneReference type for use with
// apply.
func DNSZoneReference() *DNSZoneReferenceApplyConfiguration {
	return &DNSZoneReferenceApplyConfiguration{}
}

// WithName sets the Name field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Name field is set to the value of the last call.
func (b *DNSZoneReferenceApplyConfiguration) WithName(value string) *DNSZoneReferenceApplyConfiguration {
	b.Name = &value
	return b
}
