{{- if .Values.gatewayAPI.enabled }}
apiVersion: gateway.networking.k8s.io/v1
kind: GatewayClass
metadata:
  name: openzro-private
  labels:
    {{- include "openzro-operator.labels" . | nindent 4 }}
spec:
  controllerName: "gateway.openzro.io/controller"
---
apiVersion: gateway.networking.k8s.io/v1
kind: GatewayClass
metadata:
  name: openzro-public
  labels:
    {{- include "openzro-operator.labels" . | nindent 4 }}
spec:
  controllerName: "gateway.openzro.io/controller"
{{- end }}
