apiVersion: openzro.io/v1alpha1
kind: SetupKey
metadata:
  name: sidecar
  namespace: default
spec:
  name: sidecar
  ephemeral: true
---
apiVersion: openzro.io/v1alpha1
kind: SidecarProfile
metadata:
  name: test
  namespace: default
spec:
  setupKeyRef:
    name: sidecar
  podSelector:
    matchLabels:
      app: ubuntu
